# These are supported funding model platforms
# 100% of the money will be rolled back into bounties for projects on the list!

github: Divide-By-0
ethereum: 0x4272DFE20cF1C4d9d9e9CEb28e2b6AF80269Cb65
custom: https://etherscan.io/address/0x4272DFE20cF1C4d9d9e9CEb28e2b6AF80269Cb65
